### PR TITLE
Use Cinnamon 2.15.1

### PR DESCRIPTION
**Pull request by marcospereira**

### CODE REVIEW

**Review by ignasi35 — APPROVED** [review]

**Comment by ignasi35** [comment]
+1 to enabling auto-merge on this repo

**Comment by ignasi35** [comment]
> +1 to enabling auto-merge on this repo

Interesting. Enabling `auto-merge` in the settings may only apply to PR's created after enabling the setting.

So, I've enabled auto-merge but can't use it here.

**Comment by marcospereira** [comment]
> So, I've enabled auto-merge but can't use it here.

Aha! I was looking at it now and wondering why I cannot enable it here. :-)

**Comment by marcospereira** [comment]
It is still downloading 2.15.0, though (because https://github.com/lightbend/akka-platform-dependencies/pull/6 was not released yet). :-(

**Comment by ignasi35** [comment]
I just pushed tag v0.1.5 to get a new release of the BOM

**Pull request merged**
